package com.codequest.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    RATE_LIMITED,
    CODE_RUNNER_UNAVAILABLE,
    AI_SERVICE_UNAVAILABLE,
    AI_RESPONSE_INVALID,
    EXTERNAL_SERVICE_ERROR,
    INTERNAL_ERROR
}
